module.exports = {
  rules: {
    'no-var': 'error',
    eqeqeq: ['error', 'always'],
    'for-direction': 'error',
    'prefer-template': ['error'],
    'no-duplicate-imports': 'error',
    'no-const-assign': 'error',
    'no-debugger': 'warn',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': [
      'error',
      {
        allowEmptyCatch: true,
      },
    ],
    'no-empty-pattern': 'error',
    'no-global-assign': 'error',
    'no-invalid-this': 'error',
    'no-labels': 'error',
    'no-loss-of-precision': 'error',
    'no-new': 'error',
    'no-new-object': 'error',
    'no-return-assign': ['error', 'always'],
    'no-sparse-arrays': 'error',
    'array-callback-return': 'error',
    'default-case-last': 'error',
    'no-dupe-else-if': 'error',
    'no-caller': 'error',
    'no-empty-character-class': 'error',
    'no-extra-boolean-cast': 'error',
    'no-implicit-coercion': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': ['error', 'both'],
    'no-irregular-whitespace': 'error',
    'no-lone-blocks': 'error',
    'no-misleading-character-class': 'error',
    'no-shadow-restricted-names': 'error',
    'spaced-comment': 'error',
  },
};
